### ISSUE TITLE
Code 3

### ISSUE THREAD

**Issue by Gruutak** [MRokas/PogoPlayer#3]
Hi, I'm receiving an error when running the script...

```
Failed to complete the tutorial... ERROR: { [StopError: Status code 3 received from RPC]
  name: 'StopError',
  message: 'Status code 3 received from RPC' }
```

It get spammed on the terminal... Any idea on what could it be?

**Comment by Sevenanths** [comment]
Did you already accept the terms and conditions via the Pokémon Trainer Club website? If so, just run
`node name.js -a ptc -u LOGIN -p PASS -l 00.00,00.00 -u TRAINER-NAME` and you should be good.

**Comment by Gruutak** [comment]
@Sevenanths Thank you. That worked.
