### ISSUE TITLE
pogobuf required/installed

### ISSUE THREAD

**Issue by DeviantEng** [MRokas/PogoPlayer#4]
Getting the below error:
[root@server PogoPlayer]# node pogo.js

/opt/PogoPlayer/pogo.js:3
const pogobuf = require("pogobuf");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

All I did with install nodejs and npm, `git clone`, `npm install`, and setup accounts.csv as needed (with trainer name).  Get the above error when I try to run.  I did try running `npm install pogobuf`, which installed, but did not fix my problem.

**Comment by JarodKY** [comment]
I'm having the same issue

**Comment by MRokas** [comment]
`node --version` returns 4.x.x I suppose?

Either get 6.x.x or change `const`  keywords to `var`

**Comment by DeviantEng** [comment]
@MRokas 

```
[root@server PogoPlayer]# node --version
v0.10.42
```

Haha, so the nodejs version in EPEL is probably pretty outdated.  Changing `const` to `var` caused another error, so I'm going to get nodejs updated to v6 and go that way.  Will report back.

**Comment by DeviantEng** [comment]
Yup, node version was the problem.  

I used this:
https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora

To get nodejs v6.x and it's working fine now.  

Thanks!

**Comment by echo465** [comment]
Same issue.  Ubuntu 14.04.5 LTS apt installs v0.10.25.
