### ISSUE TITLE
Cannot read property 'push' of null

### ISSUE THREAD

**Issue by RiberoD07** [MRokas/PogoPlayer#5]
## General Description
Whenever i run node pogo.js or node name.js with parameters being passed i get the following error
tried it with 5 accounts at first then with just 1, tried increasing the timeout all attempts resulted in the same error
Failed to initialize client... ERROR: { Error: operation timed out after 9032 ms, 5 tries with error: Cannot read property 'push' of null

## Expected Behavior

Expected behaviour when running node pogo.js is for it to do stuff, encounter tos, accept tos, among other things and to successfully verify and complete the tutorial for the specified accounts

## Actual Behaviour
upon running it times out and catches the error. 
Occurs before console.log(`Logged in. Doing stuff in ${timeOut/1000} seconds`);  is ran.

## Possible Solution

the type error Cannot read property 'push' of null seems to be hinting at it trying to push to an object instead of an array. could also be because the item it is trying to push isn't in local storage which would cause it to be of type null

## Steps to Reproduce (for bugs)

1. git clone
2. npm install
3. renamed accounts.csv.example to accounts.csv and put in my information
4. node pogo.js

## Your Environment

* Environment name and version: npm: 3.10.3 node: v6.3.1
* Operating System and version: Windows 10 x64

**Comment by MRokas** [comment]
This error is thrown by pogobuf package.

**Comment by revoqed** [comment]
how do you fix it then?

**Comment by MRokas** [comment]
I would be able to help if you gave full error stack trace

**Comment by MRokas** [comment]
It should be working with latest pogobuf, you should do `npm install`

https://github.com/cyraxx/pogobuf/commit/cfd4abaf675d263028a0e4451bf74ec2b886eaf1
